pipeline {
    agent any

    environment {
        DOCKERHUB = credentials('dockerhub-sofia')   // ID de la credencial en Jenkins
        IMAGE_NAME = "sofiasoler16044/gym-tracker"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build JAR') {
            steps {
                sh './mvnw -ntp clean package -DskipTests'
            }
        }

        stage('Build Docker image') {
            steps {
                sh """
                  docker build -t ${IMAGE_NAME}:${env.BUILD_NUMBER} -t ${IMAGE_NAME}:latest .
                """
            }
        }

        stage('Push Docker image') {
            steps {
                sh """
                  echo ${DOCKERHUB_PSW} | docker login -u ${DOCKERHUB_USR} --password-stdin
                  docker push ${IMAGE_NAME}:${env.BUILD_NUMBER}
                  docker push ${IMAGE_NAME}:latest
                """
            """
        }
    }
}
