package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class WorkoutAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkoutAllPropertiesEquals(Workout expected, Workout actual) {
        assertWorkoutAutoGeneratedPropertiesEquals(expected, actual);
        assertWorkoutAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkoutAllUpdatablePropertiesEquals(Workout expected, Workout actual) {
        assertWorkoutUpdatableFieldsEquals(expected, actual);
        assertWorkoutUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkoutAutoGeneratedPropertiesEquals(Workout expected, Workout actual) {
        assertThat(actual)
            .as("Verify Workout auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkoutUpdatableFieldsEquals(Workout expected, Workout actual) {
        assertThat(actual)
            .as("Verify Workout relevant properties")
            .satisfies(a -> assertThat(a.getWorkoutDate()).as("check workoutDate").isEqualTo(expected.getWorkoutDate()))
            .satisfies(a -> assertThat(a.getDurationMinutes()).as("check durationMinutes").isEqualTo(expected.getDurationMinutes()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertWorkoutUpdatableRelationshipsEquals(Workout expected, Workout actual) {
        assertThat(actual)
            .as("Verify Workout relationships")
            .satisfies(a -> assertThat(a.getExercises()).as("check exercises").isEqualTo(expected.getExercises()));
    }
}
